# Generated by Django 4.1.10 on 2023-08-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='NULL', max_length=11, null='False', unique=True),
            preserve_default='False',
        ),
    ]
