# Generated by Django 4.1.10 on 2023-09-01 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_email_alter_profile_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_id',
            field=models.CharField(db_column='session_ID', default=datetime.datetime(2023, 9, 1, 14, 6, 56, 419547), max_length=256),
        ),
    ]
